"""Focused tests for the y-websocket wire protocol and awareness clocks."""

import pycrdt
import pytest

from app.collaboration import websocket as websocket_module
from app.collaboration.document import DocumentManager
from app.collaboration.presence import AwarenessStore
from app.collaboration.protocol import (
    MAX_SAFE_INTEGER,
    SYNC_STEP1,
    SYNC_STEP2,
    SYNC_UPDATE,
    AuthMessage,
    AwarenessEntry,
    AwarenessMessage,
    AwarenessQuery,
    ProtocolError,
    SyncMessage,
    decode_var_uint,
    encode_awareness_message,
    encode_permission_denied,
    encode_sync_message,
    encode_sync_step1,
    encode_var_uint,
    parse_message,
)
from app.models import RoleEnum


class _FakeWebSocket:
    def __init__(self) -> None:
        self.sent: list[bytes] = []

    async def send_bytes(self, data: bytes) -> None:
        self.sent.append(data)


class _FakeDocumentManager:
    def __init__(self) -> None:
        self.applied: list[tuple[str, bytes]] = []

    def encode_state_as_update(
        self,
        _session_id: str,
        _state_vector: bytes,
    ) -> bytes:
        return b"server-delta"

    def apply_update(self, session_id: str, update: bytes) -> None:
        self.applied.append((session_id, update))


@pytest.mark.parametrize(
    "value",
    [0, 1, 127, 128, 16_383, 16_384, 2**32 - 1, MAX_SAFE_INTEGER],
)
def test_lib0_var_uint_round_trip(value: int) -> None:
    encoded = encode_var_uint(value)

    decoded, offset = decode_var_uint(encoded)

    assert decoded == value
    assert offset == len(encoded)


def test_known_y_websocket_v3_sync_frames() -> None:
    # Generated by y-websocket 3.1.0 + y-protocols 1.0.7 for an empty Y.Doc.
    step1 = parse_message(bytes.fromhex("00000100"))
    step2 = parse_message(bytes.fromhex("0001020000"))

    assert step1 == SyncMessage(subtype=SYNC_STEP1, payload=b"\x00")
    assert step2 == SyncMessage(subtype=SYNC_STEP2, payload=b"\x00\x00")
    assert not step1.modifies_document
    assert step2.modifies_document
    assert SyncMessage(SYNC_UPDATE, b"").modifies_document


def test_known_y_websocket_v3_awareness_frame() -> None:
    # Generated by y-protocols for client 1104808336 at awareness clock 1.
    frame = bytes.fromhex(
        "011f019093e88e0401177b2275736572223a7b226e616d65223a22416461227d7d"
    )

    message = parse_message(frame)

    assert isinstance(message, AwarenessMessage)
    assert message.entries[0].client_id == 1_104_808_336
    assert message.entries[0].clock == 1
    assert message.entries[0].state == {"user": {"name": "Ada"}}


def test_awareness_frame_round_trip_preserves_protocol_state() -> None:
    entries = (
        AwarenessEntry(
            client_id=42,
            clock=7,
            state={"user": {"name": "Zoë"}, "cursor": {"line": 3}},
            encoded_state=('{"user":{"name":"Zoë"},"cursor":{"line":3}}'),
        ),
    )

    decoded = parse_message(encode_awareness_message(entries))

    assert isinstance(decoded, AwarenessMessage)
    assert decoded.entries == entries


def test_awareness_store_applies_clocks_and_disconnect_removal() -> None:
    store = AwarenessStore()
    owner = object()
    other_owner = object()
    original = AwarenessEntry(7, 1, {"user": "Ada"}, '{"user":"Ada"}')
    stale = AwarenessEntry(7, 1, {"user": "Old"}, '{"user":"Old"}')
    newer = AwarenessEntry(7, 2, {"user": "Grace"}, '{"user":"Grace"}')

    assert store.apply_update("room", owner, (original,), now=1) == (original,)
    assert store.apply_update("room", owner, (stale,), now=2) == ()
    assert store.apply_update("room", other_owner, (newer,), now=3) == (newer,)
    assert store.remove_owner("room", owner) == ()

    removed = store.remove_owner("room", other_owner)

    assert len(removed) == 1
    assert removed[0].client_id == 7
    assert removed[0].clock == 2
    assert removed[0].state is None
    assert store.active_entries("room") == ()


def test_awareness_store_prunes_stale_states() -> None:
    store = AwarenessStore(stale_timeout=30)
    entry = AwarenessEntry(9, 1, {"user": "Ada"}, '{"user":"Ada"}')
    store.apply_update("room", object(), (entry,), now=10)

    assert store.prune_stale("room", now=40) == ()
    removed = store.prune_stale("room", now=40.1)

    assert len(removed) == 1
    assert removed[0].state is None


def test_query_and_permission_denied_frames_are_protocol_native() -> None:
    assert isinstance(parse_message(b"\x03"), AwarenessQuery)

    denied = parse_message(encode_permission_denied("Viewers cannot edit"))

    assert denied == AuthMessage(subtype=0, reason="Viewers cannot edit")


@pytest.mark.parametrize(
    ("frame", "error"),
    [
        (b"", "empty"),
        (b"\x80", "truncated"),
        (b"\x80" * 8 + b"\x00", "more than 8 bytes"),
        (b"\x00\x00", "truncated"),
        (b"\x00\x09\x00", "unknown Yjs sync subtype"),
        (b"\x03\x00", "trailing"),
        (b"\x7f", "unknown y-websocket message type"),
        (b"\x01\x01\x80", "truncated"),
    ],
)
def test_malformed_frames_are_rejected(frame: bytes, error: str) -> None:
    with pytest.raises(ProtocolError, match=error):
        parse_message(frame)


def test_pycrdt_sync_payloads_converge_through_framed_protocol() -> None:
    manager = DocumentManager()
    session_id = "49ab32d9-25ca-420a-b79b-d55b93146ce8"
    client = pycrdt.Doc()
    client["monaco"] = pycrdt.Text()
    client["monaco"].insert(0, "print('hello')")

    server_step1 = parse_message(
        encode_sync_step1(manager.get_state_vector(session_id))
    )
    assert isinstance(server_step1, SyncMessage)
    client_step2 = parse_message(
        encode_sync_message(
            SYNC_STEP2,
            client.get_update(server_step1.payload),
        )
    )
    assert isinstance(client_step2, SyncMessage)
    manager.apply_update(session_id, client_step2.payload)

    reconnecting_client = pycrdt.Doc()
    reconnecting_client["monaco"] = pycrdt.Text()
    client_step1 = parse_message(encode_sync_step1(reconnecting_client.get_state()))
    assert isinstance(client_step1, SyncMessage)
    reconnecting_client.apply_update(
        manager.encode_state_as_update(session_id, client_step1.payload)
    )

    assert manager.read_text(session_id) == "print('hello')"
    assert str(reconnecting_client["monaco"]) == "print('hello')"


@pytest.mark.asyncio
async def test_viewer_can_request_sync_but_cannot_submit_updates(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    socket = _FakeWebSocket()
    manager = _FakeDocumentManager()
    monkeypatch.setattr(websocket_module, "doc_manager", manager)

    await websocket_module._handle_binary_message(
        socket,
        "room",
        RoleEnum.viewer,
        "ada",
        encode_sync_step1(b"state-vector"),
    )
    sync_response = parse_message(socket.sent.pop())

    assert sync_response == SyncMessage(SYNC_STEP2, b"server-delta")
    assert manager.applied == []

    await websocket_module._handle_binary_message(
        socket,
        "room",
        RoleEnum.viewer,
        "ada",
        encode_sync_message(SYNC_UPDATE, b"forbidden-update"),
    )
    denied = parse_message(socket.sent.pop())

    assert isinstance(denied, AuthMessage)
    assert "cannot edit" in denied.reason
    assert manager.applied == []


@pytest.mark.asyncio
async def test_editor_step2_is_applied_and_broadcast_as_normal_update(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    source = _FakeWebSocket()
    peer = _FakeWebSocket()
    manager = _FakeDocumentManager()
    monkeypatch.setattr(websocket_module, "doc_manager", manager)
    monkeypatch.setattr(
        websocket_module,
        "_rooms",
        {
            "room": [
                (source, "user-1", "ada", RoleEnum.editor),
                (peer, "user-2", "grace", RoleEnum.viewer),
            ]
        },
    )

    await websocket_module._handle_binary_message(
        source,
        "room",
        RoleEnum.editor,
        "ada",
        encode_sync_message(SYNC_STEP2, b"client-delta"),
    )

    assert manager.applied == [("room", b"client-delta")]
    assert parse_message(source.sent[0]) == SyncMessage(
        SYNC_UPDATE,
        b"client-delta",
    )
    assert peer.sent == source.sent
